#!/usr/bin/env python3
"""Builds the distributable: dist/sync.pyz plus its dist/sync.bat wrapper.

Both files are generated; nothing in dist/ is edited by hand. Standard library
only, like the tool itself -- `python build.py` is the whole toolchain.
"""

import shutil
import sys
import zipapp
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
SRC = REPO_ROOT / "src"
DIST = REPO_ROOT / "dist"

# Same logic as the wrapper has always had: prefer the `py -3` launcher, fall
# back to `python`, and pass the child's exit code straight back to the shell.
BAT = """\
@echo off
rem Generated by build.py -- do not edit. Keep it next to sync.pyz,
rem inside a directory included in the Windows PATH.
setlocal
set "SYNC_APP=%~dp0sync.pyz"
py -3 --version >nul 2>nul
if errorlevel 1 (
    python "%SYNC_APP%" %*
) else (
    py -3 "%SYNC_APP%" %*
)
exit /b %errorlevel%
"""


def _wanted(path: Path) -> bool:
    """Keeps the sources out of the archive's bytecode leftovers."""
    return "__pycache__" not in path.parts and path.suffix != ".pyc"


def build(dist: Path = DIST) -> Path:
    """(Re)creates `dist` from `src` and returns the path of the archive.

    No `main=` argument: `src/__main__.py` is shipped as a real file, because
    the one zipapp would generate discards the exit code.
    """
    if dist.exists():
        shutil.rmtree(dist)
    dist.mkdir(parents=True)

    app = dist / "sync.pyz"
    zipapp.create_archive(SRC, target=app, interpreter="/usr/bin/env python3",
                          compressed=True, filter=_wanted)
    # create_archive sets the executable bit itself on POSIX when an
    # interpreter is given, which is what makes the symlink install work.
    (dist / "sync.bat").write_text(BAT, encoding="ascii", newline="\r\n")
    return app


if __name__ == "__main__":
    app = build()
    print(f"Built {app}")
    print(f"Put {app.parent} on your PATH (or link {app.name} into a folder "
          "already on it) and call 'sync' from any folder.")
    sys.exit(0)
