#!/usr/bin/env python3
"""Entry point of the zipapp (and of `python src`).

Written by hand rather than generated by `zipapp --main`: the template zipapp
generates calls `main()` and throws the return value away, which would make
every run exit 0 -- including the ones that report errors.
"""

from cli import main

if __name__ == "__main__":
    raise SystemExit(main())
